blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import (
    BlogListView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
)
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path("blog/", BlogListView.as_view(), name="blog_list"),
    path("blog/create/", BlogCreateView.as_view(), name="blog_create"),
    path("blog/<int:pk>/", cache_page(60)(BlogDetailView.as_view()), name="blog_detail"),
    path("blog/<int:pk>/update/", BlogUpdateView.as_view(), name="blog_update"),
    path("blog/<int:pk>/delete/", BlogDeleteView.as_view(), name="blog_delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from users.models import User

NULLABLE = {"null": True, "blank": True}


class Blog(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="Заголовок",
        help_text="Введите название заголовка",
    )
    description = models.TextField(
        verbose_name="Описание",
        help_text="Введите описание",
        **NULLABLE,
    )
    photo = models.ImageField(
        verbose_name="Изображение(превью)",
        upload_to="products",
        **NULLABLE,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=False, verbose_name="Опубликовано")
    views_count = models.PositiveIntegerField(default=0, verbose_name="Просмотры")
    owner = models.ForeignKey(
        User,
        verbose_name="Владелец",
        on_delete=models.SET_NULL,
        help_text="Выберите владельца",
        **NULLABLE,
    )

    class Meta:
        verbose_name = "Запись"
        verbose_name_plural = "Записи"
        ordering = ["name"]

    def __str__(self):
        return f"{self.name}"

blog/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm, BooleanField
from blog.models import Blog


class StyleMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input"
            else:
                field.widget.attrs["class"] = "form-control"


class BlogForm(StyleMixin, ModelForm):
    class Meta:
        model = Blog
        exclude = (
            "created_at",
            "views_count",
        )

    def clean_name(self):
        name = self.cleaned_data["name"].lower()
        forbidden_words = [
            "казино",
            "криптовалюта",
            "крипта",
            "биржа",
            "дешево",
            "бесплатно",
            "обман",
            "полиция",
            "радар",
        ]
        for word in forbidden_words:
            if word in name:
                raise ValidationError("Нельзя добавлять запрещенные слова в название")
        return name

    def clean_description(self):
        description = self.cleaned_data["description"].lower()
        forbidden_words = [
            "казино",
            "криптовалюта",
            "крипта",
            "биржа",
            "дешево",
            "бесплатно",
            "обман",
            "полиция",
            "радар",
        ]
        for word in forbidden_words:
            if word in description:
                raise ValidationError("Нельзя добавлять запрещенные слова в название")
        return description

blog/views.py
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from blog.forms import BlogForm
from blog.models import Blog


class BlogListView(ListView):
    model = Blog

    def get_queryset(self):
        return super().get_queryset().filter(is_published=True)


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogCreateView(CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy("blog:blog_list")


class BlogUpdateView(UpdateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy("blog:blog_list")

    def get_success_url(self):
        return reverse_lazy("blog:blog_detail", kwargs={"pk": self.object.pk})


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy("blog:blog_list")

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <form class="row text-center" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text">Действительно вы хотети удалить {{ object.name }}?</p>
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                    <div class="row">
                        <div class="col mb-4">
                            <button type="submit" class="btn btn-danger">Удалить</button>
                            <a class="btn btn-outline-primary" href="{% url 'blog:blog_list' %}"
                               role="button">Отмена</a>
                        </div>
                    </div>

                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/home.html' %}
{% load my_ff %}
{% block content %}
<div class="row text-center">
    <div class="col-8">
        <div class="card mb-3 box-shadow d-flex flex-row">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ object.name | title }}</h4>
                <img src="{{ blog.photo | media_filter }}" class="card-img-top img-fluid mb-3"
                     style="width: 50%; height: auto; object-fit: cover;">
                <p>Дата создания: {{ object.created_at }}</p>
                <div class="d-flex justify-content-end mb-0">
                    <p>Кол-во просмотров: {{ object.views_count }}</p>
                </div>
            </div>
        </div>
        <a class="btn btn-outline-primary" href="{% url 'blog:blog_list' %}" role="button">Вернуться</a>
        <a class="btn btn-outline-primary" href="{% url 'blog:blog_update' object.pk %}" role="button">Изменить</a>
        <a class="btn btn-outline-primary" href="{% url 'blog:blog_delete' object.pk %}" role="button">Удалить</a>
    </div>
    <div class="col-4">
        <div class="card-body">
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <li>{{ object.description }}</li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="mb-3 btn btn-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/home.html' %}
{% load my_ff %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col">

        </div>
    </div>
    <div class="row text-center">
        {% for blog in object_list %}
        <div class="col-4 mb-4">
            <div class="card h-100 mb-4 box-shadow">
                <img src="{{ blog.photo | media_filter }}" class="card-img-top">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ blog.name|title }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    </ul>
                    <a class="btn btn-outline-primary" href="{% url 'blog:blog_detail' blog.pk %}" role="button">Подробнее</a>
                    <a class="btn btn-outline-primary" href="{% url 'blog:blog_update' blog.pk %}" role="button">Изменить</a>
                    <a class="btn btn-outline-primary" href="{% url 'blog:blog_delete' blog.pk %}" role="button">Удалить</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}