blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import (
    BlogListView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
)
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path("blog/", BlogListView.as_view(), name="blog_list"),
    path("blog/create/", BlogCreateView.as_view(), name="blog_create"),
    path("blog/<int:pk>/", cache_page(60)(BlogDetailView.as_view()), name="blog_detail"),
    path("blog/<int:pk>/update/", BlogUpdateView.as_view(), name="blog_update"),
    path("blog/<int:pk>/delete/", BlogDeleteView.as_view(), name="blog_delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from users.apps import UsersConfig
from users.views import (
    CustomLogoutView,
    RegisterView,
    ProfileView,
    verify,
    PasswordResetView,
)

app_name = UsersConfig.name

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("verify/<str:token>/", verify, name="verify"),
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("reset_password/", PasswordResetView.as_view(), name="reset_password"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name="@Email")
    is_active = models.BooleanField(default=False, verbose_name="Активирован")

    token = models.CharField(
        max_length=100, verbose_name="Токен", null=True, blank=True
    )

    avatar = models.ImageField(
        upload_to="users/", verbose_name="Аватар", null=True, blank=True
    )
    phone = models.CharField(
        max_length=35, verbose_name="Телефон", null=True, blank=True
    )
    region = models.CharField(
        max_length=50, verbose_name="Регион", null=True, blank=True
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import (
    UserCreationForm,
    UserChangeForm,
    PasswordResetForm,
)
from django.forms import HiddenInput, EmailField, EmailInput

from catalog.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ("email", "password1", "password2")


class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ("email", "first_name", "last_name", "phone", "avatar")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["password"].widget = HiddenInput()


class CustomPasswordResetForm(PasswordResetForm):
    email = EmailField(widget=EmailInput(attrs={"class": "form-control"}))

users/views.py
import secrets
import random

from django.contrib.auth.hashers import make_password
from django.contrib.auth import logout
from django.core.mail import send_mail
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView, UpdateView, FormView

from config.settings import EMAIL_HOST_USER
from users.forms import UserRegisterForm, UserProfileForm, CustomPasswordResetForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = "users/register.html"
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f"http://{host}/users/verify/{token}/"
        send_mail(
            subject="Активация аккаунта",
            message=f"Для активации аккаунта, перейдите по ссылке: {url}",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


def verify(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse("users:login"))


class CustomLogoutView(View):
    def get(self, request):
        logout(request)
        return redirect("/")  # Перенаправляет на главную страницу


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy("users:profile")

    def get_object(self, queryset=None):
        return self.request.user


class PasswordResetView(FormView):
    form_class = CustomPasswordResetForm
    template_name = "users/password_reset.html"
    success_url = reverse_lazy("users:login")

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            email = form.cleaned_data.get("email")
            user = User.objects.get(email=email)
            new_password = "".join(
                random.choices("abcdefghijklmnopqrstuvwxyz0123456789", k=9)
            )
            user.password = make_password(new_password)
            user.save()
            send_mail(
                subject="Восстановление пароля",
                message="Ваш новый пароль: {}".format(new_password),
                from_email=EMAIL_HOST_USER,
                recipient_list=[user.email],
            )
        return redirect("users:login")

users/templates/users/login.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="container">
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Вход
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="p-2 btn btn-outline-primary">Войти</button>
                        <a class="p-2 btn btn-outline-primary" href="{% url 'users:reset_password' %}">Восстановить пароль</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="container">
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Восстановление пароля
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Восстановить</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="container">
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Регистрация
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Регистрация</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="container">
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Профиль
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}