blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import (
    BlogListView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
)
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path("blog/", BlogListView.as_view(), name="blog_list"),
    path("blog/create/", BlogCreateView.as_view(), name="blog_create"),
    path("blog/<int:pk>/", cache_page(60)(BlogDetailView.as_view()), name="blog_detail"),
    path("blog/<int:pk>/update/", BlogUpdateView.as_view(), name="blog_update"),
    path("blog/<int:pk>/delete/", BlogDeleteView.as_view(), name="blog_delete"),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.views import (
    ContactView,
    ProductListView,
    ProductDetailView,
    ProductUpdateView,
    ProductCreateView,
    ProductDeleteView,
    CategoryListView,
)
from catalog.apps import CatalogConfig

app_name = CatalogConfig.name

urlpatterns = [
    path("", ProductListView.as_view(), name="product_list"),
    path("contact/", ContactView.as_view(), name="contact"),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path("product/create/", ProductCreateView.as_view(), name="product_create"),
    path("product/<int:pk>/", cache_page(60)(ProductDetailView.as_view()), name="product_detail"),
    path("product/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("product/<int:pk>/delete/", ProductDeleteView.as_view(), name="product_delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import User

NULLABLE = {"null": True, "blank": True}


class Category(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="Имя категории",
        help_text="Введите название категории",
        **NULLABLE,
    )
    description = models.TextField(
        verbose_name="Описание категории",
        help_text="Введите описание категории",
        **NULLABLE,
    )

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="Наименование",
        help_text="Введите наименование продукта",
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        verbose_name="Категория",
        help_text="Выберите категорию",
        null=True,
        blank=True,
        related_name="products",
    )
    description = models.TextField(
        verbose_name="Описание продукта",
        help_text="Введите описание продукта",
        **NULLABLE,
    )
    photo = models.ImageField(
        verbose_name="Изображение(превью)",
        upload_to="products",
        **NULLABLE,
    )
    purchase_price = models.DecimalField(
        verbose_name="Цена",
        max_digits=10,
        decimal_places=2,
        help_text="Введите цену в рублях",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published = models.BooleanField(
        default=False,
        verbose_name="Опубликовано",
    )
    owner = models.ForeignKey(
        User,
        verbose_name="Владелец",
        on_delete=models.SET_NULL,
        **NULLABLE,
        related_name="products",
    )

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["name", "purchase_price"]
        permissions = [
            ("can_cancel_published", "Может отменять публикацию продукта"),
            ("can_edit_description", "Может менять описание продукта"),
            ("can_edit_category", "Может менять категорию продукта"),
        ]

    def __str__(self):
        return f"{self.name}"


class Version(models.Model):
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        verbose_name="Продукт",
        help_text="Выберите продукт",
        related_name="versions",
    )
    version_name = models.CharField(
        max_length=100,
        verbose_name="Название версии",
        help_text="Введите Название версии",
    )
    version_number = models.PositiveIntegerField(
        verbose_name="Номер версии",
        help_text="Введите Номер версии",
        unique=True,
    )
    current_version = models.BooleanField(
        default=False,
        verbose_name="Текущая версия",
    )

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"
        ordering = ["version_number"]

    def __str__(self):
        return f"{self.product.name} - {self.version_name} ({self.version_number})"

catalog/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm, BooleanField
from catalog.models import Product


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input"
            else:
                field.widget.attrs["class"] = "form-control"


class ProductForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        fields = "__all__"


class ProductManagerForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        fields = ("published", "description", "category")

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['owner'].disabled = True

    def clean_name(self):
        name = self.cleaned_data["name"].lower()
        forbidden_words = [
            "казино",
            "криптовалюта",
            "крипта",
            "биржа",
            "дешево",
            "бесплатно",
            "обман",
            "полиция",
            "радар",
        ]
        for word in forbidden_words:
            if word in name:
                raise ValidationError("Нельзя добавлять запрещенные слова в название")
        return name

    def clean_description(self):
        description = self.cleaned_data["description"].lower()
        forbidden_words = [
            "казино",
            "криптовалюта",
            "крипта",
            "биржа",
            "дешево",
            "бесплатно",
            "обман",
            "полиция",
            "радар",
        ]
        for word in forbidden_words:
            if word in description:
                raise ValidationError("Нельзя добавлять запрещенные слова в название")
        return description

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    TemplateView,
    CreateView,
    UpdateView,
    DeleteView,
)

from catalog.forms import ProductForm, ProductManagerForm
from catalog.models import Product, Version, Category
from catalog.services import get_categories, get_products


class ContactView(TemplateView):
    template_name = "catalog/contact.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Contact"
        return context


class CategoryListView(ListView):
    model = Category
    template_name = 'catalog/catalog_list.html'
    context_object_name = 'categories'

    def get_queryset(self):
        return get_categories()


class ProductListView(ListView):
    model = Product
    template_name = 'catalog/product_list.html'  # Укажите шаблон для отображения списка продуктов

    def get_queryset(self):
        return get_products()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        for product in context["object_list"]:
            current_version = product.versions.filter(current_version=True).first()
            if current_version:
                product.current_version = current_version
        return context


class ProductDetailView(DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = context["object"]
        current_version = product.versions.filter(current_version=True).first()
        if current_version:
            context["current_version"] = current_version
        return context


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:product_list")

    def get_initial(self):
        initial = super().get_initial()
        initial["owner"] = self.request.user
        return initial

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:product_list")

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        ProductFormset = inlineformset_factory(
            Product, Version, form=ProductForm, extra=1
        )
        if self.request.method == "POST":
            context_data["formset"] = ProductFormset(
                self.request.POST, instance=self.object
            )
        else:
            context_data["formset"] = ProductFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data["formset"]
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(
                self.get_context_data(form=form, formset=formset)
            )

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if (
                user.has_perm("catalog.can_cancel_published")
                and user.has_perm("catalog.can_edit_description")
                and user.has_perm("catalog.can_edit_category")
        ):
            return ProductManagerForm
        raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy("catalog:product_list")

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <form class="row text-center" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text">Действительно вы хотети удалить {{ object.name }}?</p>
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                    <div class="row">
                        <div class="col mb-4">
                            <button type="submit" class="btn btn-danger">Удалить</button>
                            <a class="btn btn-outline-primary" href="{% url 'catalog:blog_list' %}"
                               role="button">Отмена</a>
                        </div>
                    </div>

                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/home.html' %}
{% load my_ff %}
{% block content %}
<div class="row text-center">
    <div class="col-8">
        <div class="card mb-3 box-shadow d-flex flex-row">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ object.name | title }}</h4>
                <img src="{{ blog.photo | media_filter }}" class="card-img-top img-fluid mb-3"
                     style="width: 50%; height: auto; object-fit: cover;">
                <p>Дата создания: {{ object.created_at }}</p>
                <div class="d-flex justify-content-end mb-0">
                    <p>Кол-во просмотров: {{ object.views_count }}</p>
                </div>
            </div>
        </div>
        <a class="btn btn-outline-primary" href="{% url 'catalog:blog_list' %}" role="button">Вернуться</a>
        <a class="btn btn-outline-primary" href="{% url 'catalog:blog_update' object.slug %}" role="button">Изменить</a>
        <a class="btn btn-outline-primary" href="{% url 'catalog:blog_delete' object.slug %}" role="button">Удалить</a>
    </div>
    <div class="col-4">
        <div class="card-body">
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <li>{{ object.description }}</li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/home.html' %}
{% load my_ff %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col">
            <a class="mb-3 btn btn-outline-primary" href="{% url 'catalog:blog_create' %}" role="button">Создать запись в блоге</a>
        </div>
    </div>
    <div class="row text-center">
        {% for blog in object_list %}
        <div class="col-4 mb-4">
            <div class="card h-100 mb-4 box-shadow">
                <img src="{{ blog.photo | media_filter }}" class="card-img-top">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ blog.name|title }}</h4>
                </div>
                <div class="card-body">

                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">

                    </ul>
                    <a class="btn btn-outline-primary" href="{% url 'catalog:blog_detail' slug=blog.slug %}" role="button">Подробнее</a>
                    <a class="btn btn-outline-primary" href="{% url 'catalog:blog_update' slug=blog.slug %}" role="button">Изменить</a>
                    <a class="btn btn-outline-primary" href="{% url 'catalog:blog_delete' slug=blog.slug %}" role="button">Удалить</a>
                </div>

            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/catalog_list.html
{% extends 'catalog/home.html' %}
{% load my_ff %}
{% block content %}
<h1>Список категорий</h1>
<ul>
    {% for category in categories %}
    <li>{{ category.name }}: {{ category.description }}</li>
    {% endfor %}
</ul>
{% endblock %}

catalog/templates/catalog/contact.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/home.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    {% include 'catalog/includes/inc_menu.html' %}
</div>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
    {% if user.is_authenticated %}
        <a class="mb-3 btn btn-outline-primary text-center" href="{% url 'catalog:product_create' %}" role="button">Добавить товар</a>
        или <a class="mb-3 btn btn-outline-primary" href="{% url 'blog:blog_create' %}" role="button">Добавить запись в блог</a>
    {% endif %}
</div>

<div class="container">
    {% block content %}
    {% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2024</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <form class="text-center" method="post" enctype="multipart/form-data">
            <div class="card">
                <div class="card-header">
                    <p class="card-text">Действительно вы хотите удалить {{ object.name }}?</p>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                </div>
                <div class="row">
                    <div class="col mb-4">
                        <button type="submit" class="btn btn-danger">Удалить</button>
                        <a class="btn btn-outline-primary" href="{% url 'catalog:product_detail' object.pk %}"
                           role="button">Отмена</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/home.html' %}
{% load my_ff %}
{% block content %}
<div class="row text-center">
    <div class="col-8">
        <div class="card mb-4 box-shadow d-flex flex-row">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ object.name | title }}</h4>
                <img src="{{ product.photo | media_filter }}" class="card-img-top img-fluid"
                     style="width: 50%; height: auto; object-fit: cover;">
            </div>
        </div>
    </div>
    <div class="col-4">
        <div class="card-body">
            <h1 class="card-title pricing-card-title">Цена: {{ object.purchase_price }}руб.</h1>
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <li>{{ object.description }}</li>
            </ul>
            <div class="text-end">
                {% if current_version %}
                <p><strong>Активная версия: </strong>{{ current_version.version_name }} ({{ current_version.version_number }})</p>
                {% endif %}
            </div>

            <a class="btn btn-outline-primary" href="{% url 'catalog:product_list' %}" role="button">Вернуться</a>
            {% if perms.catalog.can_cancel_published and perms.catalog.can_edit_description and perms.catalog.can_edit_category or user == catalog.owner %}
            <a class="btn btn-outline-primary" href="{% url 'catalog:product_update' object.pk %}"
               role="button">Изменить</a>
            {% endif %}
            {% if user.is_superuser %}
            <a class="btn btn-outline-primary" href="{% url 'catalog:product_delete' object.pk %}"
               role="button">Удалить</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Товар
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="mb-3 btn btn-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Версия
                        </h3>
                    </div>
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                            {{ form.as_p }}
                        {% endfor %}
                    </div>
                    <button type="submit" class="mb-3 btn btn-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </div>
        </div>

    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/home.html' %}
{% load my_ff %}
{% block content %}
<div class="container">
    <div class="row text-center">
        {% for product in object_list %}
        <div class="col-4 mb-4">
            <div class="card h-100 mb-4 box-shadow">
                <img src="{{ product.photo | media_filter }}" class="card-img-top">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ product.name|title }}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ product.purchase_price }} руб.</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{ product.description | truncatechars:100 }}</li>
                    </ul>
                <div class="card-body">
                    {% if product.current_version %}
                    ({{ product.current_version.version_name }} - {{ product.current_version.version_number }})
                    {% endif %}
                </div>
                <a class="btn btn-outline-primary" href="{% url 'catalog:product_detail' product.pk %}"
                   role="button">Просмотр</a>
                {% if perms.catalog.can_cancel_published and perms.catalog.can_edit_description and perms.catalog.can_edit_category or user == catalog.owner %}
                <a class="btn btn-outline-primary" href="{% url 'catalog:product_update' product.pk %}"
                   role="button">Изменить</a>
                {% endif %}
                {% if user.is_superuser %}
                <a class="btn btn-outline-primary" href="{% url 'catalog:product_delete' product.pk %}"
                   role="button">Удалить</a>
                {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}